/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis1;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Kuis1 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis1
     */
    public Kuis1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Nilai = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Matpel = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel5.setText("Absen");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 130, 50, 30);

        jLabel6.setText("Matpel");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 170, 50, 30);

        jLabel7.setText("Nilai");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 210, 50, 30);

        jLabel9.setText("Nama");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 90, 50, 30);
        getContentPane().add(Nilai);
        Nilai.setBounds(170, 210, 80, 30);
        getContentPane().add(Nama);
        Nama.setBounds(170, 90, 200, 30);
        getContentPane().add(Absen);
        Absen.setBounds(170, 130, 70, 30);
        getContentPane().add(Matpel);
        Matpel.setBounds(170, 170, 200, 30);

        OK.setBackground(new java.awt.Color(255, 204, 204));
        OK.setText("PROSES");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(190, 260, 90, 30);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 320, 400, 230);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("PENILAIAN SISWA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 20, 200, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 490, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
       String nama = Nama.getText();
       String absen = Absen.getText();
       String mapel = Matpel.getText();
       double nilai = Double.parseDouble(Nilai.getText());
       String nilaiakhir;
       if(nilai>100)
           nilaiakhir = "Masukkan Ulang Nilai";
       else if(nilai<75)
           nilaiakhir = "Tidak Lulus";
       else if(nilai>75)
           nilaiakhir = "Lulus";
       else
           nilaiakhir = "Masukkan Ulang";
       Hasil.setText("=================== PENILAIAN SISWA ===================\n"+"\nNama\t: "+nama+"\nAbsen\t: "+absen+"\nMata Pelajaran\t: "+mapel+
               "\nNilai\t: "+nilai+"\nKeterangan\t: "+nilaiakhir);
         
    }//GEN-LAST:event_OKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JTextField Matpel;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nilai;
    private javax.swing.JButton OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
