/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Kuis2;

/**
 *
 * @author ASUS
 */
public class Kuis2 extends javax.swing.JFrame {

    /**
     * Creates new form Kuis2
     */
    public Kuis2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        h4 = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();
        h3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Diskon = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel2.setText("Harga Barang 2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 120, 100, 50);

        jLabel3.setText("Harga Barang 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 80, 100, 50);

        jLabel5.setText("Harga Barang 3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 160, 100, 50);

        jLabel4.setText("Diskon");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 240, 100, 50);
        getContentPane().add(h4);
        h4.setBounds(210, 210, 110, 30);
        getContentPane().add(h1);
        h1.setBounds(210, 90, 110, 30);
        getContentPane().add(h2);
        h2.setBounds(210, 130, 110, 30);
        getContentPane().add(h3);
        h3.setBounds(210, 170, 110, 30);

        jLabel6.setText("Rp");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(170, 210, 20, 30);

        jLabel7.setText("Rp");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 90, 20, 30);

        jLabel8.setText("Rp");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 130, 20, 30);

        jLabel9.setText("Rp");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 170, 20, 30);

        hapus.setBackground(new java.awt.Color(102, 255, 102));
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus);
        hapus.setBounds(160, 300, 71, 25);

        keluar.setBackground(new java.awt.Color(102, 255, 102));
        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(270, 300, 77, 25);

        proses.setBackground(new java.awt.Color(102, 255, 102));
        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(40, 300, 79, 25);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 350, 360, 260);

        jLabel10.setText("Harga Barang 4");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 200, 100, 50);
        getContentPane().add(Diskon);
        Diskon.setBounds(210, 250, 70, 30);

        jLabel11.setText("%");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 250, 20, 30);

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 1, 24)); // NOI18N
        jLabel1.setText("    PEMBAYARAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 10, 250, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 650);

        setBounds(0, 0, 422, 693);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        int harga1 = Integer.parseInt(h1.getText());
        int harga2 = Integer.parseInt(h2.getText());
        int harga3 = Integer.parseInt(h3.getText());
        int harga4 = Integer.parseInt(h4.getText());
        double diskon = Double.parseDouble(Diskon.getText());
        double total;
        double proses;
        double hargabayar;
        
        total = harga1+harga2+harga3+harga4;
        proses = total*(diskon/100);
        hargabayar = total-proses;
        
        hasil.setText("==================== KASIR =======================\n"+"Harga barang 1\t\t: "+harga1+"\nHarga barang 2\t\t: "+harga2+"\nHarga barang 3\t\t: "+harga3+"\nHarga barang 4\t\t: "+harga4+
                "\nDiskon\t\t: "+diskon+"%"+"\nTotal Harga\t\t: Rp"+total+"\nTotal Bayar\t\t: Rp"+hargabayar);
    }//GEN-LAST:event_prosesActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
    h1.setText(" ");
    h2.setText(" ");
    h3.setText(" ");
    h4.setText(" ");
    Diskon.setText(" ");
    hasil.setText(" ");
    }//GEN-LAST:event_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kuis2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kuis2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JTextField h4;
    private javax.swing.JButton hapus;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JButton proses;
    // End of variables declaration//GEN-END:variables
}
