/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan4;

/**
 *
 * @author ASUS
 */
public class latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form latihan4
     */
    public latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Absen = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdT = new javax.swing.JRadioButton();
        rdR = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        h4 = new javax.swing.JCheckBox();
        h1 = new javax.swing.JCheckBox();
        h2 = new javax.swing.JCheckBox();
        h3 = new javax.swing.JCheckBox();
        Keluar = new javax.swing.JButton();
        Oke = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("       BIODATA SISWA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 20, 150, 30);

        jLabel4.setText("Hobi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 190, 50, 30);

        jLabel6.setText("Nama");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 70, 50, 30);

        jLabel7.setText("Nama");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 70, 50, 30);
        getContentPane().add(Absen);
        Absen.setBounds(120, 110, 60, 30);
        getContentPane().add(Nama);
        Nama.setBounds(120, 70, 220, 30);

        jLabel5.setText("Absen");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 110, 50, 30);

        rdT.setBackground(new java.awt.Color(153, 255, 255));
        rdT.setText("TKJ");
        rdT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTActionPerformed(evt);
            }
        });
        getContentPane().add(rdT);
        rdT.setBounds(190, 150, 60, 40);

        rdR.setBackground(new java.awt.Color(153, 255, 255));
        rdR.setText("RPL");
        rdR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdRActionPerformed(evt);
            }
        });
        getContentPane().add(rdR);
        rdR.setBounds(120, 150, 60, 40);

        jLabel8.setText("Jurusan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 150, 50, 40);

        h4.setBackground(new java.awt.Color(153, 255, 255));
        h4.setText("Designer");
        h4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h4ActionPerformed(evt);
            }
        });
        getContentPane().add(h4);
        h4.setBounds(240, 220, 110, 30);

        h1.setBackground(new java.awt.Color(153, 255, 255));
        h1.setText("Programming");
        getContentPane().add(h1);
        h1.setBounds(120, 190, 110, 30);

        h2.setBackground(new java.awt.Color(153, 255, 255));
        h2.setText("Animator");
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });
        getContentPane().add(h2);
        h2.setBounds(120, 220, 110, 30);

        h3.setBackground(new java.awt.Color(153, 255, 255));
        h3.setText("Teknisi");
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });
        getContentPane().add(h3);
        h3.setBounds(240, 190, 110, 30);

        Keluar.setText("Exit");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar);
        Keluar.setBounds(240, 260, 80, 30);

        Oke.setText("Submit");
        Oke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkeActionPerformed(evt);
            }
        });
        getContentPane().add(Oke);
        Oke.setBounds(60, 260, 80, 30);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(150, 260, 79, 30);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 310, 360, 200);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void h4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h4ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h2ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_h3ActionPerformed

    private void rdRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdRActionPerformed

    private void rdTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdTActionPerformed

    private void OkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkeActionPerformed
        String nama = Nama.getText();
        String absen = Absen.getText();
        String jurusan;
        String hobi = " ";
        
        if(rdR.isSelected())
            jurusan = "Rekayasa Perangkat Lunak";
        else if(rdT.isSelected())
            jurusan = "Teknik Jaringan Komputer";
        else
            jurusan = "Pilih Salah Satu";
        
        if(h1.isSelected())
            hobi+=h1.getText()+", ";
        if(h2.isSelected())
            hobi+=h2.getText()+", ";
        if(h3.isSelected())
            hobi+=h3.getText()+", ";
        if(h4.isSelected())
            hobi+=h4.getText()+", ";
        
        Hasil.setText("==================BIODATA SISWA==================\n"+"\nNama Siswa\t: "+nama+"\nAbsen Siswa\t: "+absen+
                "\nJurusan\t: "+jurusan+"\nHobi Anda\t: "+hobi);
    }//GEN-LAST:event_OkeActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
       Hasil.setText(" ");
       Nama.setText(" ");
       Absen.setText(" ");
       h1.setSelected(false);
       h2.setSelected(false);
       h3.setSelected(false);
       h4.setSelected(false);
    }//GEN-LAST:event_HapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Oke;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox h1;
    private javax.swing.JCheckBox h2;
    private javax.swing.JCheckBox h3;
    private javax.swing.JCheckBox h4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdR;
    private javax.swing.JRadioButton rdT;
    // End of variables declaration//GEN-END:variables
}
