/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lanjutan3;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Lb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Hb = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Sk = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Vk = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Jb = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Vbola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PROGRAM PENCARI VOLUME BANGUN RUANG");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 260, 30);

        jPanel1.setLayout(null);

        jLabel2.setText("Masukkan Tinggi    :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 130, 140, 30);

        jLabel3.setText("Masukkan Panjang  :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 30, 140, 30);

        jLabel4.setText("Masukkan Lebar     :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 80, 140, 30);
        jPanel1.add(Tb);
        Tb.setBounds(190, 130, 110, 30);

        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(320, 130, 17, 30);
        jPanel1.add(Pb);
        Pb.setBounds(190, 30, 110, 30);

        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 30, 17, 30);
        jPanel1.add(Lb);
        Lb.setBounds(190, 80, 110, 30);

        jLabel7.setText("cm");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 80, 17, 30);

        Hb.setText("Hitung");
        Hb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbActionPerformed(evt);
            }
        });
        jPanel1.add(Hb);
        Hb.setBounds(200, 200, 69, 25);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel8.setText("Masukkan Panjang  Sisi");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 30, 140, 30);
        jPanel2.add(Sk);
        Sk.setBounds(20, 70, 110, 30);

        jLabel9.setText("cm");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 66, 41, 30);

        Vk.setText("Volume");
        Vk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VkActionPerformed(evt);
            }
        });
        jPanel2.add(Vk);
        Vk.setBounds(40, 110, 79, 25);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel10.setText("Masukkan Panjang  Jari-Jari");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 30, 180, 30);
        jPanel3.add(Jb);
        Jb.setBounds(20, 70, 110, 30);

        jLabel11.setText("cm");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(140, 66, 41, 30);

        Vbola.setText("Volume");
        Vbola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VbolaActionPerformed(evt);
            }
        });
        jPanel3.add(Vbola);
        Vbola.setBounds(40, 110, 79, 25);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(30, 70, 380, 380);

        setBounds(0, 0, 475, 535);
    }// </editor-fold>//GEN-END:initComponents

    private void HbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbActionPerformed
        int panjang, lebar, tinggi;
        
        panjang = Integer.parseInt(Pb.getText());
        lebar = Integer.parseInt(Lb.getText());
        tinggi = Integer.parseInt(Tb.getText());
        int hasil = panjang*lebar*tinggi;
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok adalah "+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Eroor : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_HbActionPerformed

    private void VkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VkActionPerformed
        int sisi;
        sisi = Integer.parseInt(Sk.getText());
        int hasil = sisi*sisi*sisi;
        try{
            JOptionPane.showMessageDialog(null, "Volume Kubus adalah "+hasil,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Eroor : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_VkActionPerformed

    private void VbolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VbolaActionPerformed
        float jari;
        jari = Integer.parseInt(Jb.getText());
        float hasil1 = (float) (4/3*3.14*jari*jari*jari);
        try{
            JOptionPane.showMessageDialog(null, "Volume Bola adalah "+hasil1,"luas",
                    JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Eroor : "+e,"Gagal",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_VbolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hb;
    private javax.swing.JTextField Jb;
    private javax.swing.JTextField Lb;
    private javax.swing.JTextField Pb;
    private javax.swing.JTextField Sk;
    private javax.swing.JTextField Tb;
    private javax.swing.JButton Vbola;
    private javax.swing.JButton Vk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
